name = "caddy"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://bvgxievzgugjtnlokkgt.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z3hpZXZ6Z3VnanRubG9ra2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzOTM5ODIsImV4cCI6MjA3ODk2OTk4Mn0.1ZyhGDkCUd_w-1BSYGb0pWkgsNsqQ5dBWpjCwg1m5YY"

# Environment variables for preview deployments
[env.preview.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://bvgxievzgugjtnlokkgt.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z3hpZXZ6Z3VnanRubG9ra2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzOTM5ODIsImV4cCI6MjA3ODk2OTk4Mn0.1ZyhGDkCUd_w-1BSYGb0pWkgsNsqQ5dBWpjCwg1m5YY"

